export const FETCH_PRODUCTS_BEGIN = "FETCH_PRODUCTS_BEGIN";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";
export const CHANGE_OFFSET = "CHANGE_OFFSET";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const CREATE_PRODUCT_BEGIN = "CREATE_PRODUCT_BEGIN";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAILURE = "CREATE_PRODUCT_FAILURE";
export const DELETE_PRODUCT_BEGIN = "DELETE_PRODUCT_BEGIN";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";
export const UPDATE_PRODUCT_BEGIN = "UPDATE_PRODUCT_BEGIN";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE";

export const FETCH_AUTHENTICATION = "FETCH_AUTHENTICATION";
export const REMOVE_AUTHENTICATION = "REMOVE_AUTHENTICATION";
export const GET_AUTH_ERRORS = "GET_AUTH_ERRORS";
export const REMOVE_AUTH_ERRORS = "REMOVE_AUTH_ERRORS";

// cart
export const ADDITEM_TOCART = "ADDITEM_TOCART";
export const DELETEITEM_FROMCART = "DELETEITEM_FROMCART";
export const LOADALLITEMSFROM_DB = "LOADALLITEMSFROM_DB";
export const BEGINLOADINGFROM_DB = "BEGINLOADINGFROM_DB";
export const FINISHLOADINGFROM_DB = "FINISHLOADINGFROM_DB";

//order
export const LOADALLORDERSFROM_DB = "LOADALLORDERSFROM_DB";
export const BEGINLOADINGORDERSFROM_DB = "BEGINLOADINGORDERSFROM_DB";
export const FINISHLOADINGORDERSFROM_DB = "FINISHLOADINGORDERSFROM_DB";
export const FETCHSHIPPINGADDRESS = "FETCHSHIPPINGADDRESS";
export const CHANGE_WAREHOUSE = "CHANGE_WAREHOUSE"
export const GEOCODE_BEGIN = "GEOCODE_BEGIN"
export const GEOCODE_SUCCESS = "GEOCODE_SUCCESS"
export const GEOCODE_FAIL = "GEOCODE_FAIL"
export const CHANGE_ORDER_ID = "CHANGE_ORDER_ID"

export const CLOSE_MODAL = "CLOSE_MODAL";
export const OPEN_MODAL = "OPEN_MODAL";
export const SET_MODAL_PROPS = "SET_MODAL_PROPS";
