export const FETCH_PRODUCTS_BEGIN = "FETCH_PRODUCTS_BEGIN";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";
export const CHANGE_OFFSET = "CHANGE_OFFSET";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const CREATE_PRODUCT_BEGIN = "CREATE_PRODUCT_BEGIN"
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS"
export const CREATE_PRODUCT_FAILURE = "CREATE_PRODUCT_FAILURE"

export const FETCH_AUTHENTICATION = "FETCH_AUTHENTICATION";
export const REMOVE_AUTHENTICATION = "REMOVE_AUTHENTICATION";
export const GET_AUTH_ERRORS = "GET_AUTH_ERRORS";
export const REMOVE_AUTH_ERRORS = "REMOVE_AUTH_ERRORS";

// cart
export const ADDITEM_TOCART = "ADDITEM_TOCART";
export const DELETEITEM_FROMCART = "DELETEITEM_FROMCART";
export const GETITEMSFROM_DBCART = "GETITEMSFROM_DBCART";
