## schoolsupply
INSERT INTO `product` (`p_name`,`quantity`,`price`,`weight`,`description`,`imgPath`,`type`, `warehouse`) VALUES ('Ticonderoga The World Best Pencils',20,3.50,0.7500,'Ten pencils per pack. Worlds best pencils','https://i5.walmartimages.com/asr/f7cb71ca-7753-4ce2-a42e-098593fa5f0c_1.5d7544ede3facfb6f45d1445b36c2512.jpeg','supply', 1);
INSERT INTO `product` (`p_name`,`quantity`,`price`,`weight`,`description`,`imgPath`,`type`, `warehouse`) VALUES ('BIC Pencil XTra Life',82,5.50,0.8900,'40 per pack','https://smedia.webcollage.net/rwvfp/wc/cp/1536151245233_b8922b1d-b5b0-41de-b755-73dab84c96fc/module/bic/_cp/products/1536072499946/tab-bf7eefdb-b9f5-4c6d-9375-6af5ea50ee43/1d8c422a-81ca-4ff6-84c0-56fd821711e9.jpg.w1920.jpg','supply', 1);
INSERT INTO `product` (`p_name`,`quantity`,`price`,`weight`,`description`,`imgPath`,`type`, `warehouse`) VALUES ('Allary Eraser Combo Pack',12,2.50,0.6300,'7 erasers per pack','http://www.studentsupply.com/images/761.jpg','supply', 1);
INSERT INTO `product` (`p_name`,`quantity`,`price`,`weight`,`description`,`imgPath`,`type`, `warehouse`) VALUES ('Lead Refills- .7mm/24',24,9.20,0.3300,'Maxco Mechanical Pencil Refills','https://www.studentsupply.com/images/5853.jpg','supply', 2);
INSERT INTO `product` (`p_name`,`quantity`,`price`,`weight`,`description`,`imgPath`,`type`, `warehouse`) VALUES ('Pocket Calculator with Lanyard',12,28.59,1.2200,' Convenient calculator is only 3-3/4" x 2-1/4" and fits neatly in a pocket.','https://www.studentsupply.com/images/300624.jpg','supply', 2);

## furniture
INSERT INTO `product` (`p_name`,`quantity`,`price`,`weight`,`description`,`imgPath`,`type`, `warehouse`) VALUES ('Martha Stewart Collection Bergen Mirror',5,399.00,7.025,' Up the elegance factor of your bedroom in a useful way.','https://slimages.macysassets.com/is/image/MCY/products/4/optimized/9453514_fpx.tif?op_sharpen=1&wid=1230&hei=1500&fit=fit,1&$filterxlrg$','furniture', 1);
INSERT INTO `product` (`p_name`,`quantity`,`price`,`weight`,`description`,`imgPath`,`type`, `warehouse`) VALUES ('Martha Stewart Collection Bergen 3-Drawer Nightstand',7,699.00,45.521,'The brilliant fusion of classic elegance and modern design aesthetics.','https://slimages.macysassets.com/is/image/MCY/products/0/optimized/9453550_fpx.tif?op_sharpen=1&wid=1230&hei=1500&fit=fit,1&$filterxlrg$','furniture', 1);
INSERT INTO `product` (`p_name`,`quantity`,`price`,`weight`,`description`,`imgPath`,`type`, `warehouse`) VALUES ('Rachael Ray Highline 2-Pc. Vanity Set',12,1498.00,245.521,' Gorgeous vanity desk and full length mirror set.','https://slimages.macysassets.com/is/image/MCY/products/6/optimized/8848936_fpx.tif?op_sharpen=1&wid=1230&hei=1500&fit=fit,1&$filterxlrg$','furniture', 2);
INSERT INTO `product` (`p_name`,`quantity`,`price`,`weight`,`description`,`imgPath`,`type`, `warehouse`) VALUES ('Grove Hill II Outdoor Cast Aluminum 7-Pc. Dining Set',30,5269.00,312.021,'The textured open-work design and handsome pewter.','https://slimages.macysassets.com/is/image/MCY/products/4/optimized/10755534_fpx.tif?op_sharpen=1&wid=1230&hei=1500&fit=fit,1&$filterxlrg$','furniture', 2);
INSERT INTO `product` (`p_name`,`quantity`,`price`,`weight`,`description`,`imgPath`,`type`, `warehouse`) VALUES ('Cayla Loveseat Settee',2,629.00,95.010,'The plush cushions and warm, walnut-finish frame make it perfect.','https://slimages.macysassets.com/is/image/MCY/products/7/optimized/8639477_fpx.tif?op_sharpen=1&wid=1230&hei=1500&fit=fit,1&$filterxlrg$','furniture', 2);

## computer
INSERT INTO `product` (`p_name`,`quantity`,`price`,`weight`,`description`,`imgPath`,`type`, `warehouse`) VALUES ('Microsoft - Surface Laptop 2',50,899.00,7.6,'Next-generation Surface Laptop 2 with improved speed and performance.','https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6298/6298022_sd.jpg;maxHeight=640;maxWidth=550','computer', 1);
INSERT INTO `product` (`p_name`,`quantity`,`price`,`weight`,`description`,`imgPath`,`type`, `warehouse`) VALUES ('Apple - MacBook Pro® - 13" Display',33,1299.99,8.0,'It has the brightest, most colorful Mac notebook display.','https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5721/5721723_sd.jpg;maxHeight=640;maxWidth=550','computer', 1);
INSERT INTO `product` (`p_name`,`quantity`,`price`,`weight`,`description`,`imgPath`,`type`, `warehouse`) VALUES ('Lenovo - 130-15AST 15.6" Laptop',15,299.99,12.0,'Improve productivity with this Lenovo Ideapad laptop.','https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6323/6323661_sd.jpg;maxHeight=640;maxWidth=550','computer', 2);
INSERT INTO `product` (`p_name`,`quantity`,`price`,`weight`,`description`,`imgPath`,`type`, `warehouse`) VALUES ('Apple - MacBook Pro - Space Gray',24,2199.99,6.9,'The new MacBook Pro has 6-core Intel Core processors.','https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5998/5998604_sd.jpg;maxHeight=640;maxWidth=550','computer', 2);
INSERT INTO `product` (`p_name`,`quantity`,`price`,`weight`,`description`,`imgPath`,`type`, `warehouse`) VALUES ('HP - ENVY',31,807.99,8.9,'HP ENVY x360 Convertible 2-in-1 Laptop.', 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6237/6237358_sd.jp','computer', 2);

## printer
INSERT INTO `product` (`p_name`,`quantity`,`price`,`weight`,`description`,`imgPath`,`type`, `warehouse`) VALUES ('HP - ENVY 5055 Printer',12,119.99,33.30,'Get affordable prints and increased versatility.','https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6191/6191401cv12d.jpg;maxHeight=640;maxWidth=550','printer', 1);
INSERT INTO `product` (`p_name`,`quantity`,`price`,`weight`,`description`,`imgPath`,`type`, `warehouse`) VALUES ('HP - OfficeJet 3830 Wireless Printer',5,49.99,45.2,'Print, copy, scan and fax photos and documents all with a single device.','https://pisces.bbystatic.com/image2/BestBuy_US/images/products/4363/4363407ld.jpg;maxHeight=640;maxWidth=550','printer', 1);
INSERT INTO `product` (`p_name`,`quantity`,`price`,`weight`,`description`,`imgPath`,`type`, `warehouse`) VALUES ('Canon - PIXMA TR8520 Wireless Printer',22,99.99,49.5,'It has five individual ink cartridges for simple replacement.','https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6042/6042708_sd.jpg;maxHeight=1000;maxWidth=1000','printer', 1);
INSERT INTO `product` (`p_name`,`quantity`,`price`,`weight`,`description`,`imgPath`,`type`, `warehouse`) VALUES ('Epson - WorkForce Pro WF-3720 Wireless Printer',65,79.99,52.0,'Get high-quality document copies fast with this Epson WorkForce all-in-one printer.','https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5732/5732904_sd.jpg;maxHeight=640;maxWidth=550','printer', 2);
INSERT INTO `product` (`p_name`,`quantity`,`price`,`weight`,`description`,`imgPath`,`type`, `warehouse`) VALUES ('Epson - WorkForce ET-16500 EcoTank',13,999.99,75.1,'The super-sized ink tanks are easy to fill and can last for up to 11,000 color pages.','https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5512/5512500_sd.jpg;maxHeight=640;maxWidth=550','printer', 2);

## other
INSERT INTO `product` (`p_name`,`quantity`,`price`,`weight`,`description`,`imgPath`,`type`, `warehouse`) VALUES ('Apple - 11-Inch iPad Pro',27,949.99,4.2025,'The new 11-inch iPad Pro features an advanced Liquid Retina.','https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5985/5985630cv13d.jpg;maxHeight=640;maxWidth=550','other', 1);
INSERT INTO `product` (`p_name`,`quantity`,`price`,`weight`,`description`,`imgPath`,`type`, `warehouse`) VALUES ('Amazon - Fire HD Kids Edition',13,129.99,3.6,'The fast quad-core processor consists of four high-performance 1.3 GHz cores.','https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6293/6293764_sd.jpg;maxHeight=640;maxWidth=550','other', 1);
INSERT INTO `product` (`p_name`,`quantity`,`price`,`weight`,`description`,`imgPath`,`type`, `warehouse`) VALUES ('Samsung - Galaxy Tab A ',45,279.99,5.2500,'It has a 10-inch screen for easy viewing.','https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5364/5364800_sd.jpg;maxHeight=640;maxWidth=550','other', 1);
INSERT INTO `product` (`p_name`,`quantity`,`price`,`weight`,`description`,`imgPath`,`type`, `warehouse`) VALUES ('Amazon - Fire HD 8 - 8" - Tablet',11,99.99,5.5,'The quad-core processor and 1.5GB of RAM create a high-performing interface.','https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6293/6293710_sd.jpg;maxHeight=640;maxWidth=550','other', 2);
INSERT INTO `product` (`p_name`,`quantity`,`price`,`weight`,`description`,`imgPath`,`type`, `warehouse`) VALUES ('Samsung - Galaxy Tab E Lite',37,79.99,4.9,'A 7-inch touchscreen lets you browse websites or watch videos in virtually any light.','https://pisces.bbystatic.com/image2/BestBuy_US/images/products/4943/4943617_sd.jpg;maxHeight=1000;maxWidth=1000','other', 2);